version: "3"
services:

  grafana:
    image: grafana/grafana:6.6.2-ubuntu
    network_mode: host
#    ports:
#      - "3000:3000"
    volumes:
      # mount grafana server config
      - ./grafana/config.ini:/etc/grafana/config.ini
    depends_on:
      - influxdb
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/config.ini

  influxdb:
    image: influxdb:1.7.10
    network_mode: host
#   ports:
#      - "8086:8086"
#      - "9999:9999"
    volumes:
      - ./influxdb:/var/lib/influxdb
